version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./django_server
      dockerfile: Dockerfile
    container_name: celery
    command: celery -A django_server worker --loglevel=info
    volumes:
      - ./django_server:/app
    depends_on:
      - redis

  django_server:
    build:
      context: ./django_server
      dockerfile: Dockerfile
    container_name: django_server
    hostname: django-server
    command: >
      sh -c "rm -f /tmp/daphne.sock && python manage.py makemigrations && python manage.py migrate &&
            daphne -b 0.0.0.0 -p 8000 django_server.asgi:application"
    volumes:
      - ./django_server:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  svelte_app:
    build: ./svelte-app
    container_name: svelte_app
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./svelte-app:/app
      - /app/node_modules
    depends_on:
      - django_server

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: image-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
