# Generated by Django 4.2.14 on 2024-07-31 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('size', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(default='unknown', max_length=50)),
                ('name', models.CharField(default='default_image_name.jpg', max_length=255)),
                ('job_id', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('error', 'Error')], default='processing', max_length=64)),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
