# Generated by Django 4.2.14 on 2024-08-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='upload_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
