# Generated by Django 4.2.14 on 2024-08-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0002_imageupload_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='upload_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
